version: 2
jobs:
  build:
    docker:
      - image: cimg/node:19.7

    steps:
      - run: echo "build workflow run"

  print:
    docker:
      - image: cimg/node:19.7

    steps:
      - run: echo "deploy workflow run"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - print
