version: 2
jobs:
  build:
    docker:
      - image: cimg/node:19.7

    working_directory: ~/client

    steps:
      - checkout
      - run: echo "deploy build run"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
    docker:
      - image: cimg/node:19.7

    steps:
      - run: echo "deploy workflow run"

  workflows:
    version: 2
    test_and_deploy:
      jobs:
        - build:
        - deploy:
            requires:
              - build
